version: "3"
services:
  db:
    image: postgres
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 2G
      restart_policy:
        condition: on-failure
    networks: 
      - promise.network
    