export const OPEN = 'OPEN';

export const STARTUP = 'STARTUP';

export const WS_NOT_SUPPORT = 'WS_NOT_SUPPORT';
export const WS_SERVER_CONNECTING = 'WS_SERVER_CONNECTING';
export const WS_SERVER_CONNECTED = 'WS_SERVER_CONNECTED';
export const WS_SERVER_CONNECT_FAILED = 'WS_SERVER_CONNECT_FAILED';
export const WS_SERVER_CONNECTION_CLOSED = 'WS_SERVER_CONNECTION_CLOSED';
export const WS_SERVER_MESSAGE = 'WS_SERVER_MESSAGE';

// Server service
export const INIT_SERVER_SVC_START = 'INIT_SERVER_SVC_START';
export const INIT_SERVER_SVC_SUCCESS = 'INIT_SERVER_SVC_SUCCESS';
export const INIT_SERVER_SVC_FAILURE = 'INIT_SERVER_SVC_FAILURE';
export const SERVER_SVC_CLOSE = 'SERVER_SVC_CLOSE';

// Task service
export const INIT_TASK_SVC_START = 'INIT_TASK_SVC_START';
export const INIT_TASK_SVC_SUCCESS = 'INIT_TASK_SVC_SUCCESS';
export const INIT_TASK_SVC_FAILURE = 'INIT_TASK_SVC_FAILURE';
export const TASK_SVC_CLOSE = 'TASK_SVC_CLOSE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_FAILURE_TIMEOUT = 'LOGIN_FAILURE_TIMEOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SERVER_SELECT = 'SERVER_SELECT';
export const SERVER_GET_BEGIN = 'SERVER_GET_BEGIN';
export const SERVER_GET_SUCCESS = 'SERVER_GET_SUCCESS';
export const SERVER_GET_FAILURE = 'SERVER_GET_FAILURE';
export const SERVER_LIST_GET_BEGIN = 'SERVER_LIST_GET_BEGIN';
export const SERVER_LIST_GET_SUCCESS = 'SERVER_LIST_GET_SUCCESS';
export const SERVER_LIST_GET_FAILURE = 'SERVER_LIST_GET_FAILURE';

export const HARDWARE_POP_ADD_DIALOG = 'HARDWARE_POP_ADD_DIALOG';
export const HARDWARE_ADD_DIALOG_CANCEL = 'HARDWARE_ADD_DIALOG_CANCEL';
export const HARDWARE_ADD_DIALOG_OK = 'HARDWARE_ADD_DIALOG_OK';
export const HARDWARE_ADD_INPUT = 'HARDWARE_ADD_INPUT';

export const SERVER_CREATE = 'SERVER_CREATE';
export const SERVER_UPDATE = 'SERVER_UPDATE';
export const SERVER_DELETE = 'SERVER_DELETE';

export const SETTING_SELECT_UPGRADE_BUNDLE = 'SETTING_SELECT_UPGRADE_BUNDLE';

export const ACTIVITY_GET_START = 'ACTIVITY_GET_START';
export const ACTIVITY_GET_SUCCESS = 'ACTIVITY_GET_SUCCESS';
export const ACTIVITY_GET_FAILURE = 'ACTIVITY_GET_FAILURE';

export const TASK_LIST_GET_BEGIN = 'TASK_LIST_GET_BEGIN';
export const TASK_LIST_GET_SUCCESS = 'TASK_LIST_GET_SUCCESS';
export const TASK_LIST_GET_FAILURE = 'TASK_LIST_GET_FAILURE';
export const TASK_GET_BEGIN = 'TASK_GET_BEGIN';
export const TASK_GET_SUCCESS = 'TASK_GET_SUCCESS';
export const TASK_GET_FAILURE = 'TASK_GET_FAILURE';

// Task Message
export const TASK_CREATE = 'TASK_CREATE';
export const TASK_UPDATE = 'TASK_UPDATE';
export const TASK_DELETE = 'TASK_DELETE';

// GlobalConnection
export const SERVER_SVC_OK = 'SERVER_SVC_OK';
export const SERVER_SVC_WARNING = 'SERVER_SVC_WARNING';
export const SERVER_SVC_CRITICAL = 'SERVER_SVC_CRITICAL';
export const TASK_SVC_OK = 'TASK_SVC_OK';
export const TASK_SVC_WARNING = 'TASK_SVC_WARNING';
export const TASK_SVC_CRITICAL = 'TASK_SVC_CRITICAL';

// Desktop
export const DESKTOP_LOGIN = 'DESKTOP_LOGIN';
export const DESKTOP_CONNECTION_ERROR = 'DESKTOP_CONNECTION_ERROR';
export const DESKTOP_UNSERVICEABLE = 'DESKTOP_UNSERVICEABLE';
export const DESKTOP_READY = 'DESKTOP_READY';
