export const DESKTOP_LOGIN = 'DESKTOP_LOGIN';
export const DESKTOP_CONNECTION_ERROR = 'DESKTOP_CONNECTION_ERROR';
export const DESKTOP_UNSERVICEABLE = 'DESKTOP_UNSERVICEABLE';
export const DESKTOP_READY = 'DESKTOP_READY';

export const UNKNOWN = 'UNKNOWN';
export const GET_GLOBAL_START = 'GET_GLOBAL_START';
export const GET_GLOBAL_SUCCESS = 'GET_GLOBAL_SUCCESS';
export const GET_GLOBAL_FAILURE = 'GET_GLOBAL_FAILURE';
