export const DESKTOP_LOGIN = 'DESKTOP_LOGIN';
export const DESKTOP_CONNECTION_ERROR = 'DESKTOP_CONNECTION_ERROR';
export const DESKTOP_UNSERVICEABLE = 'DESKTOP_UNSERVICEABLE';
export const DESKTOP_READY = 'DESKTOP_READY';

export const DESKTOP_INIT_START = 'DESKTOP_INIT_START';
export const DESKTOP_INIT_SUCCESS = 'DESKTOP_INIT_SUCCESS';
export const DESKTOP_INIT_FAILURE = 'DESKTOP_INIT_FAILURE';
