export const ActionType = Object.freeze(
  {
    'SERVER_REST_ADD_START': 'SERVER_REST_ADD_START',
    'SERVER_REST_ADD_SUCCESS': 'SERVER_REST_ADD_SUCCESS',
    'SERVER_REST_ADD_MESSAGE': 'SERVER_REST_ADD_MESSAGE',
    'SERVER_REST_ADD_EXCEPTION': 'SERVER_REST_ADD_EXCEPTION',
  }
);
