export const ServerAppState = Object.freeze(
  {
    'APP_INIT_START': 'APP_INIT_START',
    'APP_INIT_SUCCESS': 'APP_INIT_SUCCESS',
    'APP_INIT_FAILURE': 'APP_INIT_FAILURE',
  }
);

export const ActionType = Object.freeze(
  {
    'APP_INIT_START': 'APP_INIT_START',
    'APP_INIT_SUCCESS': 'APP_INIT_SUCCESS',
    'APP_INIT_FAILURE': 'APP_INIT_FAILURE',
    'GET_SERVER_LIST_START': 'GET_SERVER_LIST_START',
    'GET_SERVER_LIST_SUCCESS': 'GET_SERVER_LIST_SUCCESS',
    'GET_SERVER_LIST_FAILURE': 'GET_SERVER_LIST_FAILURE',
  }
);
