version: "3.2"

services:
  httpd:
    image: httpd.promise:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks: 
      - networks_all
  server:
    image: server.promise:latest
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
      restart_policy:
        condition: on-failure
    networks: 
      - networks_all
  db:
    image: postgres:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 2G
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_PASSWORD=iforgot
      - POSTGRES_DB=promise
    networks: 
      - networks_all
      
networks:
  networks_all:
    driver: overlay
    attachable: true 
  networks_front:
    driver: overlay
    attachable: true
  networks_service:
    driver: overlay
    attachable: true
  networks_db:
    driver: overlay
    attachable: true
    