version: "3"

services:
  server:
    image: promise.server:latest
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
      restart_policy:
        condition: on-failure
    networks: 
      - promise
  db:
    image: postgres:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 2G
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_PASSWORD=iforgot
      - POSTGRES_DB=promise
    networks: 
      - promise
      
networks: 
  promise:
    driver: overlay
    