server:
  port: 8081
  context-path: /ui
  session:
    cookie:
      name: UISESSION

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: clientId
      clientSecret: secret
      accessTokenUri: http://localhost:8080/auth/oauth/token
      userAuthorizationUri: http://localhost:8080/auth/oauth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/rest/hello

spring:
  thymeleaf:
    cache: false