version: "3"
services:
  db:
    image: promise.httpd
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    networks: 
      - promise.network
    